# Data Manipulation Part 2 - Quick Review

In [59]:
vehicles_review = pd.read_csv('vehicles/vehicles.csv')

In [60]:
vehicles_review.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

## Group by

Average Engine Displacement for each number of Cylinder.

Min, Max, Average values of CO2 Emission Grams/Mile per year per Fuel Type.

## Pandas Merge

Bring those two informations back.

# Data Cleaning
> Objectives:
    - Given a messy dataset - extract meaningful information from it. 
    - Learn from the data.

In [1]:
import pandas as pd
import numpy as np

In [9]:
vehicles = pd.read_csv('vehicles/vehicles_messy.csv', low_memory=False)

In [10]:
vehicles.shape

(37843, 83)

In [11]:
vehicles.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [5]:
# display more columns on the dataframe visualization.
# pd.options.display.max_columns = 99

In [13]:
# create a copy of our dataset just for backup.
vehicles_bkp = vehicles.copy()

In [14]:
# Describing our dataset.
vehicles.describe()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,UCity,UCityA,UHighway,UHighwayA,year,youSaveSpend,charge240b,phevCity,phevHwy,phevComb
count,37843.000000,37843.000000,37843.0,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,...,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000,37843.000000
mean,17.532506,0.216169,0.0,0.023531,17.941389,4.042737,0.520149,0.327163,0.000406,0.184790,...,22.587229,0.652380,33.619221,0.933845,2000.064398,-2658.999022,0.004360,0.069313,0.068203,0.068573
std,4.575950,1.141527,0.0,0.427647,6.660360,9.645820,3.837874,3.542596,0.039918,2.904558,...,9.350163,5.284547,10.048326,6.059456,10.390588,2553.098329,0.142776,1.966806,1.871986,1.913647
min,0.060000,0.000000,0.0,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1984.000000,-22250.000000,0.000000,0.000000,0.000000,0.000000
25%,14.330870,0.000000,0.0,0.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,18.000000,0.000000,27.100000,0.000000,1990.000000,-4250.000000,0.000000,0.000000,0.000000,0.000000
50%,17.347895,0.000000,0.0,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,21.000000,0.000000,33.000000,0.000000,2001.000000,-2500.000000,0.000000,0.000000,0.000000,0.000000
75%,20.600625,0.000000,0.0,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,25.139300,0.000000,38.109600,0.000000,2009.000000,-750.000000,0.000000,0.000000,0.000000,0.000000
max,47.087143,18.311667,0.0,12.000000,138.000000,138.304000,127.000000,127.093000,5.350000,122.000000,...,197.577100,181.560900,159.100000,152.187800,2017.000000,4000.000000,7.000000,97.000000,79.000000,88.000000

# Data types of our dataset

In [15]:
vehicles.dtypes

barrels08     float64
barrelsA08    float64
charge120     float64
charge240     float64
city08          int64
               ...
modifiedOn     object
startStop      object
phevCity        int64
phevHwy         int64
phevComb        int64
Length: 83, dtype: object

In [17]:
vehicles['barrels08'].dtypes

dtype('float64')

In [18]:
vehicles['barrels08'].dtypes == 'float64'

True

In [19]:
vehicles['barrels08'].dtypes == 'int64'

False

## What if I wanted to select only the 'float64' columns?

In [21]:
selected_float_cols = []

for each_column in vehicles.columns:
    if vehicles[each_column].dtypes == 'float64':
        print(each_column)
        # i want to append only the float cols to selected_float_cols

barrels08
barrelsA08
charge120
charge240
city08U
cityA08U
cityCD
cityE
cityUF
co2TailpipeAGpm
co2TailpipeGpm
comb08U
combA08U
combE
combinedCD
combinedUF
cylinders
displ
highway08U
highwayA08U
highwayCD
highwayE
highwayUF
rangeCity
rangeCityA
rangeHwy
rangeHwyA
UCity
UCityA
UHighway
UHighwayA
charge240b

In [ ]:
vehicles[selected_float_cols]

In [ ]:
vehicles[selected_float_cols].dtypes

In [ ]:
## Convert to float ...

# Obtaining some metadata from our dataframe.

In [10]:
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  int64
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(23)
memory usage: 23.7+ MB

# Null (or Missing) values

>    - Count 
>    - <b>Mask</b> concept

In [23]:
vehicles.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [24]:
vehicles.head().isnull()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,False,False,True,False,False,False

## Let's select the mfrCode column and see how many missing values this column has.

In [26]:
vehicles['mfrCode'].isnull()

0        True
1        True
2        True
3        True
4        True
         ...
37838    True
37839    True
37840    True
37841    True
37842    True
Name: mfrCode, Length: 37843, dtype: bool

In [ ]:
# How to count it?

# How to get the percentage of missing values?

## What if I wanted to count the number of missing values for each column?

In [29]:
vehicles.isnull().sum()

barrels08         0
barrelsA08        0
charge120         0
charge240         0
city08            0
              ...
modifiedOn        0
startStop     31705
phevCity          0
phevHwy           0
phevComb          0
Length: 83, dtype: int64

## What if we wanted to count Null values for each row?
    - axis = 1

In [28]:
vehicles.isnull().sum(axis=1)

0        12
1        11
2        11
3        13
4        11
         ..
37838    11
37839    12
37840    11
37841    12
37842    10
Length: 37843, dtype: int64

## What if I wanted to select only the rows in which there are at least one missing value (in any column)?

In [78]:
# this will return True if there is any missing in each COLUMN. 
vehicles.isnull().any() 

# How can I check it for each rows? What is the syntax for checking for rows instead of columns?

barrels08     False
barrelsA08    False
charge120     False
charge240     False
city08        False
              ...
createdOn     False
startStop      True
phevCity      False
phevHwy       False
phevComb      False
Length: 82, dtype: bool

# Dropping columns
> `axis=1` or

> `columns = ['name_of_column_to_drop1', 'name_of_column_to_drop2' ,...]`

In [33]:
vehicles['modifiedOn']

0        Tue Jan 01 00:00:00 EST 2013
1        Tue Jan 01 00:00:00 EST 2013
2        Tue Jan 01 00:00:00 EST 2013
3        Tue Jan 01 00:00:00 EST 2013
4        Tue Jan 01 00:00:00 EST 2013
                     ...
37838    Tue Jan 01 00:00:00 EST 2013
37839    Tue Jan 01 00:00:00 EST 2013
37840    Tue Jan 01 00:00:00 EST 2013
37841    Tue Jan 01 00:00:00 EST 2013
37842    Tue Jan 01 00:00:00 EST 2013
Name: modifiedOn, Length: 37843, dtype: object

In [34]:
vehicles.drop('modifiedOn', axis=1)

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [37]:
vehicles.drop(columns='modifiedOn')

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,...,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [45]:
vehicles.drop(columns='modifiedOn', inplace=True)

KeyError: "['modifiedOn'] not found in axis"

# Drop columns based on condition
>    - Pandas Series

>    - Pandas Indexing

>    - Mask concept

## Lets store the number of missing values in a variable, and based on the number of missing values that column has, lets remove it or not

In [48]:
vehicles.isnull().sum()

barrels08         0
barrelsA08        0
charge120         0
charge240         0
city08            0
              ...
createdOn         0
startStop     31705
phevCity          0
phevHwy           0
phevComb          0
Length: 82, dtype: int64

In [46]:
n_missings = vehicles.isnull().sum()

In [47]:
n_missings

barrels08         0
barrelsA08        0
charge120         0
charge240         0
city08            0
              ...
createdOn         0
startStop     31705
phevCity          0
phevHwy           0
phevComb          0
Length: 82, dtype: int64

In [44]:
vehicles.shape

(37843, 82)

In [56]:
### create a condition in which you get True for the indexes that have more than 10000 columns.

In [57]:
### select from the n_missings pandas Series the ones that returned True.

In [ ]:
### get the index of that pandas series.

In [ ]:
### store it in a variable called `columns_to_drop`, for example

columns_to_drop =

In [62]:
vehicles.drop(columns=columns_to_drop)

# Understand the data (!)
>    - Deep dive into data
>    - <b>Understand the business</b> you're working with
>    - Understand how (and if) you can input those values as more meaningful information
>    - Fill not a number

## Lets get all columns where the displacement is missing.

In [65]:
# passo a passo
vehicles['displ']

0        2.0
1        4.9
2        2.2
3        5.2
4        2.2
        ...
37838    2.2
37839    2.2
37840    2.2
37841    2.2
37842    2.2
Name: displ, Length: 37843, dtype: float64

In [68]:
# get a mask of which rows are missing
# vehicles['displ'].

In [ ]:
# create a new dataframe for those rows where the displacement is missing.

In [ ]:
missing_displacement =

In [69]:
# Lets just see some columns of it.
#missing_displacement = missing_displacement[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]
missing_displacement.head(10)

In [ ]:
## There's some explanation for why the displacement is zero. What is it?

# missing_displacement[['fuelType','displ', 'cylinders']]

In [ ]:
## So now that I know this, how can I replace the missing values by the value I want?
# vehicles[['displ', 'cylinders']] = vehicles[['displ', 'cylinders']].fillna(0)

In [14]:

vehicles.groupby(by='fuelType', as_index=False).sum().query('fuelType == "Electricity"')['displ']

In [74]:
# vehicles.groupby(by='fuelType').mean()[['displ']]

## Use cases
>    - Cheque devolvido = 0 _vs_ Cheque devolvido = NaN

# Correct wrong data

In [15]:
# create a condition for which cylinders value == 0
no_cylinder = 


# create a condition for which displacement is different from 0
yes_displacement =

,year,make,model,trany,drive,fuelType,cylinders,displ
21506,1986,Mazda,RX-7,Manual 5-spd,Rear-Wheel Drive,Regular,0.0,1.3

In [ ]:
test = data[no_cylinder & yes_displacement]
test[['year', 'make', 'model', 'trany', 'drive','fuelType','cylinders', 'displ']]

In [17]:
# suppose you know this mazda has 4 cylinders and you want to input that (based on your knowledge of cars.)
data.loc[no_cylinder & yes_displacement, 'cylinders'] = 4

In [19]:
data.loc[no_cylinder & yes_displacement, 'cylinders']

21506    4.0
Name: cylinders, dtype: float64

# Types
>    - dtypes
>    - astype()

In [133]:
data.dtypes

barrels08     float64
barrelsA08    float64
charge120     float64
charge240     float64
city08          int64
               ...
createdOn      object
modifiedOn     object
phevCity        int64
phevHwy         int64
phevComb        int64
Length: 70, dtype: object

In [137]:
data['year']

0        1985
1        1985
2        1985
3        1985
4        1993
         ...
37838    1993
37839    1993
37840    1993
37841    1993
37842    1993
Name: year, Length: 37843, dtype: object

In [139]:
pd.to_datetime(data['year'], format='%Y')

0       1985-01-01
1       1985-01-01
2       1985-01-01
3       1985-01-01
4       1993-01-01
           ...
37838   1993-01-01
37839   1993-01-01
37840   1993-01-01
37841   1993-01-01
37842   1993-01-01
Name: year, Length: 37843, dtype: datetime64[ns]

In [134]:
data['year'] = data['year'].astype('object')
data['year'].dtype

dtype('O')

# String normalization

In [140]:
data.trany.value_counts()

Automatic 4-spd                     11042
Manual 5-spd                         8311
Automatic 3-spd                      3151
Automatic (S6)                       2638
Manual 6-spd                         2429
Automatic 5-spd                      2184
Manual 4-spd                         1483
Automatic 6-spd                      1432
Automatic (S8)                        960
Automatic (S5)                        824
Automatic (variable gear ratios)      681
Automatic 7-spd                       663
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        233
Auto(AM7)                             160
Auto(AV-S6)                           145
Auto(AM6)                             110
Automatic (A1)                        109
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           77
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Manual 4-spd Doubled                   17
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Manual(M7)                              3
Auto(L3)                                2
Auto(L4)                                2
Auto (AV)                               2
Automatic (AM5)                         2
Auto(AM-S9)                             1
Manual 5 spd                            1
Auto (AV-S8)                            1
Automatic (AM6)                         1
Auto (AV-S6)                            1
Automatic 6spd                          1
Auto(A1)                                1
Name: trany, dtype: int64

In [142]:
print(set(data['trany']))

{nan, 'Auto(L4)', 'Manual 5-spd', 'Manual 6-spd', 'Automatic 8-spd', 'Auto(AM-S7)', 'Manual 7-spd', 'Automatic (AV-S6)', 'Automatic (S9)', 'Automatic (A6)', 'Automatic (A1)', 'Auto(AM5)', 'Automatic (S8)', 'Automatic 3-spd', 'Auto(AV-S6)', 'Manual 5 spd', 'Auto(AM8)', 'Automatic 5-spd', 'Automatic 6-spd', 'Auto (AV)', 'Automatic (AM5)', 'Auto(AM6)', 'Manual 4-spd Doubled', 'Automatic 7-spd', 'Auto(L3)', 'Automatic (S5)', 'Automatic (S6)', 'Automatic (AV)', 'Automatic 6spd', 'Auto (AV-S6)', 'Auto(AM-S6)', 'Auto(AM-S9)', 'Automatic 4-spd', 'Auto(AM7)', 'Manual 3-spd', 'Auto(AV-S7)', 'Auto(AV-S8)', 'Auto (AV-S8)', 'Manual 4-spd', 'Automatic (variable gear ratios)', 'Automatic (S7)', 'Automatic (AM6)', 'Manual(M7)', 'Auto(A1)', 'Automatic 9-spd', 'Automatic (S4)', 'Auto(AM-S8)'}

In [143]:
print(set(data['trany'].str.replace('-', '')))

{nan, 'Auto(L4)', 'Automatic 5spd', 'Auto(AMS8)', 'Automatic (S9)', 'Automatic (A6)', 'Manual 4spd Doubled', 'Automatic (A1)', 'Auto(AVS7)', 'Auto(AM5)', 'Automatic (S8)', 'Automatic 8spd', 'Manual 5 spd', 'Auto(AM8)', 'Automatic 9spd', 'Auto(AVS6)', 'Manual 4spd', 'Manual 7spd', 'Auto (AVS8)', 'Auto (AV)', 'Automatic (AM5)', 'Auto(AM6)', 'Automatic 6spd', 'Auto(L3)', 'Automatic (S5)', 'Automatic (S6)', 'Automatic (AV)', 'Automatic 7spd', 'Auto(AMS7)', 'Manual 6spd', 'Auto(AM7)', 'Manual 5spd', 'Auto(AMS6)', 'Auto (AVS6)', 'Automatic 4spd', 'Automatic (AVS6)', 'Automatic (variable gear ratios)', 'Automatic (S7)', 'Auto(AVS8)', 'Automatic (AM6)', 'Manual(M7)', 'Manual 3spd', 'Auto(AMS9)', 'Automatic 3spd', 'Automatic (S4)', 'Auto(A1)'}

In [144]:
data['trany'] = data['trany'].str.replace('-', '')
data['trany'] = data['trany'].str.replace('Automatic', 'Auto')
data['trany'] = data['trany'].str.replace('Auto\(', 'Auto ')
data['trany'] = data['trany'].str.replace('Manual\(', 'Manual ')
data['trany'] = data['trany'].str.replace('\(', '')
data['trany'] = data['trany'].str.replace('\)', '')
print(set(data['trany']))

{nan, 'Auto 6spd', 'Auto S7', 'Auto AM5', 'Manual 4spd Doubled', 'Auto AVS6', 'Auto AM6', 'Auto AM7', 'Auto L3', 'Auto L4', 'Manual 5 spd', 'Auto AMS8', 'Auto AV', 'Auto AVS7', 'Manual 4spd', 'Auto S6', 'Auto S5', 'Auto variable gear ratios', 'Auto A1', 'Manual 7spd', 'Auto AM8', 'Auto AMS9', 'Auto 7spd', 'Auto 9spd', 'Auto 5spd', 'Auto S8', 'Manual 6spd', 'Auto 8spd', 'Manual M7', 'Manual 5spd', 'Auto S4', 'Auto S9', 'Auto AVS8', 'Auto A6', 'Auto AMS7', 'Manual 3spd', 'Auto AMS6', 'Auto 3spd', 'Auto 4spd'}

In [145]:
data.trany.value_counts()

Auto 4spd                    11042
Manual 5spd                   8311
Auto 3spd                     3151
Auto S6                       2638
Manual 6spd                   2429
Auto 5spd                     2184
Manual 4spd                   1483
Auto 6spd                     1433
Auto S8                        960
Auto S5                        824
Auto variable gear ratios      681
Auto 7spd                      663
Auto S7                        261
Auto AMS7                      256
Auto 8spd                      243
Auto S4                        233
Auto AM7                       160
Auto AVS6                      155
Auto AM6                       111
Auto A1                        110
Auto AMS6                       92
Auto 9spd                       90
Manual 3spd                     77
Manual 7spd                     68
Auto AVS7                       63
Auto AVS8                       27
Auto S9                         26
Manual 4spd Doubled             17
Auto AM5                        14
Auto AMS8                        6
Auto AV                          6
Auto AM8                         5
Auto A6                          4
Manual M7                        3
Auto L3                          2
Auto L4                          2
Auto AMS9                        1
Manual 5 spd                     1
Name: trany, dtype: int64

# Dropping or checking duplicates rows
    
>    - Dropping fully duplicate row
>    - Subset
>    - Idempotency
>    - <b>Duplicated</b>

In [146]:
before = len(data)
data = data.drop_duplicates()
after = len(data)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  0

In [154]:
data.iloc[0] = data.iloc[376]

In [156]:
mask = data.duplicated()
data[mask]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
376,23.543571,0.0,0.0,0.0,12,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,634.785714,14,0.0,0,0.0,0.0,0.0,0.0,8.0,5.0,4-Wheel or All-Wheel Drive,4951,(FFS),-1,2400,0,Regular,Regular Gasoline,-1,-1,17,0.0,0,0.0,0.0,0.0,0.0,0,0,10336,0,0,Chevrolet,Pickup 2500 4WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 4-spd,15.0,0.0,23.0769,0.0,Standard Pickup Trucks,1993,-5250,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [149]:
data.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
0,23.543571,0.0,0.0,0.0,12,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,634.785714,14,0.0,0,0.0,0.0,0.0,0.0,8.0,5.0,4-Wheel or All-Wheel Drive,4951,-1,2400,0,Regular,Regular Gasoline,-1,-1,17,0.0,0,0.0,0.0,0.0,0.0,0,0,10336,0,0,Chevrolet,Pickup 2500 4WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,15.0000,0.0,23.0769,0.0,Standard Pickup Trucks,1993,-5250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

In [150]:
before = len(data)
data = data.drop_duplicates(subset=['year','VClass'])
after = len(data)
print('Number of duplicate records dropped: ', str(before - after))

Number of duplicate records dropped:  37255

In [151]:
data

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
0,23.543571,0.0,0.0,0.0,12,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,634.785714,14,0.0,0,0.0,0.0,0.0,0.0,8.0,5.0,4-Wheel or All-Wheel Drive,4951,-1,2400,0,Regular,Regular Gasoline,-1,-1,17,0.0,0,0.0,0.0,0.0,0.0,0,0,10336,0,0,Chevrolet,Pickup 2500 4WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,15.0000,0.0,23.0769,0.0,Standard Pickup Trucks,1993,-5250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
18,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,6.0,2.8,Front-Wheel Drive,64012,-1,2150,0,Premium,Premium Gasoline,-1,-1,22,0.0,0,0.0,0.0,0.0,0.0,0,0,10013,0,17,Audi,100,Y,False,0,96,0,0.0,0.0,0.0,0.0,Auto 4spd,21.0000,0.0,31.0000,0.0,Midsize Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
118,16.480500,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,444.350000,20,0.0,0,0.0,0.0,0.0,0.0,6.0,3.8,Front-Wheel Drive,4400,-1,1650,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,10103,0,17,Buick,LeSabre,Y,False,0,109,0,0.0,0.0,0.0,0.0,Auto 4spd,21.0000,0.0,36.0000,0.0,Large Cars,1993,-1500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
156,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,2.8,4-Wheel or All-Wheel Drive,64012,-1,2250,0,Premium,Premium Gasoline,-1,-1,20,0.0,0,0.0,0.0,0.0,0.0,0,0,10138,0,34,Audi,100 quattro Wagon,N,False,0,91,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,28.0000,0.0,Small Station Wagons,1993,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
183,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,4122,-1,1600,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,10162,0,41,Buick,Century Wagon,N,False,0,96,0,0.0,0.0,0.0,0.0,Auto 3spd,23.0000,0.0,37.0000,0.0,Midsize-Large Station Wagons,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
242,16.480500,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,444.350000,20,0.0,0,0.0,0.0,0.0,0.0,4.0,2.5,Rear-Wheel Drive,4800,-1,1650,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,10215,0,0,Chevrolet,S10 Pickup 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,22.0000,0.0,33.3333,0.0,Small Pickup Trucks,1993,-1500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
358,20.600625,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,555.437500,16,0.0,0,0.0,0.0,0.0,0.0,4.0,2.5,Rear-Wheel Drive,9580,-1,2100,0,Regular,Regular Gasoline,-1,-1,17,0.0,0,0.0,0.0,0.0,0.0,0,0,1032,0,0,AM General,Post Office DJ5 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,20.0000,0.0,23.0769,0.0,Special Purpose Vehicle 2WD,1985,-3750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
461,20.600625,0.0,0.0,0.0,14,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,555.437500,16,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,4-Wheel or All-Wheel Drive,4941,-1,2550,0,Premium,Premium Gasoline,-1,-1,20,0.0,0,0.0,0.0,0.0,0.0,0,0,10412,0,0,Chevrolet,Astro AWD (cargo),N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,17.7778,0.0,27.0000,0.0,Vans,1993,-6000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
540,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,3.1,Front-Wheel Drive,4820,-1,1850,0,Regular,Regular Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,10484,0,0,Chevrolet,Lumina/APV Minivan 2WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,20.0000,0.0,29.0000,0.0,Special Purpose Vehicles,1993,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
602,19.388824,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,8.0,4.1,Front-Wheel Drive,21480,-1,1950,0,Regular,Regular Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,1054,0,0,"E. P. Dutton, Inc.",Funeral Coach,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,18.0000,0.0,29.0000,0.0,Special Purpose Vehicles,1985,-3000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
688,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,3.0,Rear-Wheel Drive,26061,-1,2250,0,Premium,Premium Gasoline,-1,-1,22,0.0,0,0.0,0.0,0.0,0.0,0,0,10617,0,0,Acura,NSX,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,30.0000,0.0,Two Seaters,1994,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
728,17.347895,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,6.0,2.8,Front-Wheel Drive,64012,-1,2150,0,Premium,Premium Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,10653,7,0,Audi,Cabriolet,Y,False,71,0,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,33.0000,0.0,Minicompact Cars,1994,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
753,13.733750,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,370.291667,24,0.0,0,0.0,0.0,0.0,0.0,4.0,1.8,Front-Wheel Drive,26025,-1,1700,0,Premium,Premium Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,13,77,10676,0,12,Acura,Integra,Y,False,0,83,0,0.0,0.0,0.0,0.0,Manual 5spd,28.0000,0.0,39.7436,0.0,Subcompact Cars,1994,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
879,25.354615,0.0,0.0,0.0,12,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,683.615385,13,0.0,0,0.0,0.0,0.0,0.0,8.0,5.0,4-Wheel or All-Wheel Drive,4961,-1,2550,0,Regular,Regular Gasoline,-1,-1,15,0.0,0,0.0,0.0,0.0,0.0,0,0,1079,0,0,Chevrolet,K10 Blazer 4WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,15.0000,0.0,21.0000,0.0,Special Purpose Vehicle 4WD,1985,-6000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
939,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,3.2,Front-Wheel Drive,26075,-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,10843,14,15,Acura,Legend,Y,False,85,94,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,29.0000,0.0,Compact Cars,1994,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1096,19.388824,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,8.0,4.0,Rear-Wheel Drive,12057,-1,2400,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,10985,0,13,BMW,740i,N,False,0,101,0,0.0,0.0,0.0,0.0,Auto 5spd,18.0000,0.0,29.0000,0.0,Midsize Cars,1994,-5250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1181,16.480500,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,444.350000,20,0.0,0,0.0,0.0,0.0,0.0,6.0,3.8,Front-Wheel Drive,4502,-1,1650,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,11060,0,17,Buick,LeSabre,Y,False,0,109,0,0.0,0.0,0.0,0.0,Auto 4spd,21.0000,0.0,36.0000,0.0,Large Cars,1994,-1500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1221,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,2.8,4-Wheel or All-Wheel Drive,64010,-1,1850,0,Regular,Regular Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,11097,0,34,Audi,100 quattro Wagon,N,False,0,91,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,29.0000,0.0,Small Station Wagons,1994,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1255,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,4406,-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,11127,0,41,Buick,Century Wagon,N,False,0,96,0,0.0,0.0,0.0,0.0,Auto 3spd,24.4444,0.0,37.0000,0.0,Midsize-Large Station Wagons,1994,-750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1301,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Rear-Wheel Drive,4422,-1,1750,0,Regular,Regular Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,11169,0,0,Chevrolet,S10 Pickup 2WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,21.0000,0.0,32.0513,0.0,Small Pickup Trucks,1994,-2000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1326,19.388824,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,Rear-Wheel Drive,4810,-1,1950,0,Regular,Regular Gasoline,-1,-1,20,0.0,0,0.0,0.0,0.0,0.0,0,0,11191,0,0,Chevrolet,C1500 Pickup 2WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,18.8889,0.0,27.0000,0.0,Standard Pickup Trucks,1994,-3000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1522,20.600625,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,555.437500,16,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,4-Wheel or All-Wheel Drive,4802,-1,2550,0,Premium,Premium Gasoline,-1,-1,19,0.0,0,0.0,0.0,0.0,0.0,0,0,11368,0,0,Chevrolet,Astro AWD (cargo),N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,18.0000,0.0,26.9231,0.0,Vans,1994,-6000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1598,25.354615,0.0,0.0,0.0,11,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,683.615385,13,0.0,0,0.0,0.0,0.0,0.0,8.0,5.7,Rear-Wheel Drive,4815,-1,2550,0,Regular,Regular Gasoline,-1,-1,16,0.0,0,0.0,0.0,0.0,0.0,0,0,11436,0,0,Chevrolet,Suburban 1500 2WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,14.0000,0.0,22.0000,0.0,Special Purpose Vehicles,1994,-6000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1758,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,3.0,Rear-Wheel Drive,26070,-1,2250,0,Premium,Premium Gasoline,-1,-1,22,0.0,0,0.0,0.0,0.0,0.0,0,0,11580,0,0,Acura,NSX,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,30.0000,0.0,Two Seaters,1995,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1797,17.347895,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,6.0,2.8,Front-Wheel Drive,64012,-1,2150,0,Premium,Premium Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,11615,7,0,Audi,Cabriolet,N,False,71,0,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,33.0000,0.0,Minicompact Cars,1995,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1823,13.733750,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,370.291667,24,0.0,0,0.0,0.0,0.0,0.0,4.0,1.8,Front-Wheel Drive,26025,-1,1700,0,Premium,Premium Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,13,77,11639,0,12,Acura,Integra,Y,False,0,83,0,0.0,0.0,0.0,0.0,Manual 5spd,28.0000,0.0,39.7436,0.0,Subcompact Cars,1995,-1750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33017,19.388824,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,6.0,3.1,Front-Wheel Drive,10301,-1,2400,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,5655,15,0,Pontiac,Grand Prix Turbo,N,False,95,0,0,0.0,0.0,0.0,0.0,Auto 4spd,18.0000,0.0,32.0513,0.0,Midsize Cars,1989,-5250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33172,16.480500,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,444.350000,20,0.0,0,0.0,0.0,0.0,0.0,6.0,3.8,Front-Wheel Drive,4421,-1,1650,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,5795,0,16,Buick,Electra/Park Avenue,Y,False,0,111,0,0.0,0.0,0.0,0.0,Auto 4spd,21.0000,0.0,36.0000,0.0,Large Cars,1989,-1500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33198,13.184400,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,355.480000,25,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Front-Wheel Drive,4111,-1,1350,0,Regular,Regular Gasoline,-1,-1,29,0.0,0,0.0,0.0,0.0,0.0,0,0,5818,0,34,Buick,Skyhawk Wagon,N,False,0,91,0,0.0,0.0,0.0,0.0,Auto 3spd,28.0000,0.0,41.0000,0.0,Small Station Wagons,1989,0,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33247,18.311667,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,5.0,2.3,Front-Wheel Drive,64012,-1,1850,0,Regular,Regular Gasoline,-1,-1,20,0.0,0,0.0,0.0,0.0,0.0,0,0,5862,0,37,Audi,100 Wagon,N,False,0,95,0,0.0,0.0,0.0,0.0,Auto 3spd,21.0000,0.0,28.2051,0.0,Midsize-Large Station Wagons,1989,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33302,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.5,Rear-Wheel Drive,4800,-1,1600,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,5911,0,0,Chevrolet,S10 Pickup 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,23.0000,0.0,36.0000,0.0,Small Pickup Trucks,1989,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33350,21.974000,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,592.466667,15,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,Rear-Wheel Drive,4826,-1,2200,0,Regular,Regular Gasoline,-1,-1,16,0.0,0,0.0,0.0,0.0,0.0,0,0,5955,0,0,Chevrolet,C1500 Pickup 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,18.0000,0.0,22.0000,0.0,Standard Pickup Trucks,1989,-4250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33569,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.5,Rear-Wheel Drive,4800,-1,1750,0,Regular,Regular Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,6151,0,0,Chevrolet,Astro 2WD (cargo),N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,21.0000,0.0,32.0000,0.0,Vans,1989,-2000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33723,18.311667,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,2.8,4-Wheel or All-Wheel Drive,4911,-1,1850,0,Regular,Regular Gasoline,-1,-1,22,0.0,0,0.0,0.0,0.0,0.0,0,0,6290,0,0,Chevrolet,S10 Blazer 4WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5spd,20.0000,0.0,32.0000,0.0,Special Purpose Vehicles,1989,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33761,20.600625,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,555.437500,16,0.0,0,0.0,0.0,0.0,0.0,6.0,2.9,4-Wheel or All-Wheel Drive,3646,-1,2100,0,Regular,Regular Gasoline,-1,-1,19,0.0,0,0.0,0.0,0.0,0.0,0,0,6324,0,0,Ford,Bronco II 4WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,18.0000,0.0,26.0000,0.0,Special Purpose Vehicle 4WD,1989,-3750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
33892,14.982273,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,1.8,Front-Wheel Drive,26021,-1,1500,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,16,79,6442,0,11,Acura,Integra,N,False,0,85,0,0.0,0.0,0.0,0.0,Auto 4spd,25.0000,0.0,34.0000,0.0,Subcompact Cars,1990,-750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34379,17.347895,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,6.0,3.8,Front-Wheel Drive,4410,-1,1750,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,6881,0,16,Buick,Electra/Park Avenue,N,False,0,111,0,0.0,0.0,0.0,0.0,Auto 4spd,20.0000,0.0,35.0000,0.0,Large Cars,1990,-2000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34407,13.733750,0.0,0.0,0.0,21,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,370.291667,24,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,4124,-1,1400,0,Regular,Regular Gasoline,-1,-1,29,0.0,0,0.0,0.0,0.0,0.0,0,0,6906,0,34,Chevrolet,Cavalier Wagon,N,False,0,89,0,0.0,0.0,0.0,0.0,Auto 3spd,27.0000,0.0,40.0000,0.0,Small Station Wagons,1990,-250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34492,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.5,Rear-Wheel Drive,4800,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,6983,0,0,Chevrolet,S10 Pickup 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,23.0000,0.0,35.0000,0.0,Small Pickup Trucks,1990,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34525,19.388824,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,Rear-Wheel Drive,4833,-1,1950,0,Regular,Regular Gasoline,-1,-1,19,0.0,0,0.0,0.0,0.0,0.0,0,0,7011,0,0,Chevrolet,C1500 Pickup 2WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,20.0000,0.0,26.9231,0.0,Standard Pickup Trucks,1990,-3000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34762,19.388824,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,4-Wheel or All-Wheel Drive,4935,-1,1950,0,Regular,Regular Gasoline,-1,-1,20,0.0,0,0.0,0.0,0.0,0.0,0,0,7225,0,0,Chevrolet,Astro AWD (cargo),N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,19.0000,0.0,27.0000,0.0,Vans,1990,-3000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34851,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,6.0,3.1,Front-Wheel Drive,4820,-1,1850,0,Regular,Regular Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,7305,0,0,Chevrolet,Lumina/APV Minivan 2WD,Y,False,0,0,0,0.0,0.0,0.0,0.0,Auto 3spd,20.0000,0.0,29.0000,0.0,Special Purpose Vehicle 2WD,1990,-2500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
34904,19.388824,0.0,0.0,0.0,15,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,522.764706,17,0.0,0,0.0,0.0,0.0,0.0,6.0,4.3,4-Wheel or All-Wheel Drive,4930,-1,1950,0,Regular,Regular Gasoline,-1,-1,20,0.0,0,0.0,0.0,0.0,0.0,0,0,7353,0,0,Chevrolet,S10 Blazer 4WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,19.0000,0.0,27.0000,0.0,Special Purpose Vehicles,1990,-3000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
35064,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,1.6,Front-Wheel Drive,38002,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,16,56,7498,0,0,Nissan,NX Coupe,N,False,0,0,0,0.0,0.0,0.0,0.0,Auto 4spd,30.0000,0.0,46.0000,0.0,Minicompact Cars,1991,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

# Low variance variables
>    - Brings no information
>    - More variance usually means more information 
>    - Percentile

In [ ]:
low_variance_cols = []

for col in vehicles._get_numeric_data():
    # if up to the ninety percentile, you are still stuck at the minimum value, remove it.
    minimum = min(data[col])
    ninety_perc = np.percentile(data[col], 90)
    #print(col, minimum, ninety_perc)
    
    if ninety_perc == minimum:
        low_variance.append(col)

print(low_variance_cols)

In [25]:
data = data.drop(low_variance, axis=1)

NameError: name 'low_variance' is not defined

In [27]:
'''
# Outliers (!)
> <b> DEMO </b>

>    - Several methods:
        - Interquartile range ($\approx$2.7$\sigma$)
        - \> 3$\sigma$ (standard-deviations)
        - Cap on specified quantile


stats = data.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

outliers = pd.DataFrame(columns=data.columns)

# Inter-quartile-range rule
# https://en.wikipedia.org/wiki/Interquartile_range#/media/File:Boxplot_vs_PDF.svg

for col in stats.index:
    iqr = stats.loc[col,'IQR']
    
    cutoff = iqr * 1.5
    lower = stats.loc[col,'25%'] - cutoff
    upper = stats.loc[col,'75%'] + cutoff
    
    mask_lower_cuttof = (data[col] < lower)
    mask_upper_cuttof = (data[col] > upper)
    
    results = data[mask_lower_cuttof | mask_upper_cuttof].copy()
    results['Outlier'] = col
    outliers = outliers.append(results, sort=False)
'''